steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hot-travel-assistant:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hot-travel-assistant:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hot-travel-assistant:$BUILD_ID'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/hot-travel-assistant:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hot-travel-assistant'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hot-travel-assistant:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,VERTEX_AI_LOCATION=us-central1,ENVIRONMENT=production,AI_PROVIDER=vertex,LLM_CACHE_DIR=/tmp/cache,LLM_CACHE_DURATION_HOURS=0,AMADEUS_CLIENT_ID=DHdjRGkND0GefDhGAAbO7Gn5lr3EgG3P,AMADEUS_CLIENT_SECRET=x91XH0FoAqeBEV5h'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/hot-travel-assistant:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/hot-travel-assistant:latest'

# Build timeout
timeout: '1200s'

options:
  # Use higher performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'