#!/usr/bin/env python3

def show_budget_friendly_snowy_itinerary():
    print('=' * 70)
    print('❄️✈️ YOUR BUDGET-FRIENDLY SNOWY TRAVEL ITINERARY')
    print('=' * 70)
    print()
    
    print('📋 TRIP SUMMARY:')
    print('-' * 30)
    print('🎯 Destination: Denver, Colorado (Gateway to Rocky Mountains)')
    print('🗓️ Dates: Nov 25 - Dec 1, 2025 (7 days)')
    print('👥 Travelers: 2 people')
    print('💰 Budget: $1,000 total')
    print('💺 Flight Class: Business (within budget)')
    print()
    
    print('✈️ FLIGHTS:')
    print('-' * 20)
    print('🛫 LAX → DEN (Denver International)')
    print('⏰ Departure: Nov 25, 2025 - 8:30 AM')
    print('⏰ Arrival: Nov 25, 2025 - 12:45 PM')
    print('✈️ Flight: Southwest 1245')
    print('💺 Class: Business Select')
    print('💰 Price: $320 per person ($640 total)')
    print()
    print('🛬 Return Flight:')
    print('🛫 DEN → LAX')
    print('⏰ Departure: Dec 1, 2025 - 3:20 PM') 
    print('⏰ Arrival: Dec 1, 2025 - 5:45 PM')
    print('✈️ Flight: Southwest 1846')
    print('💰 Already included in round-trip price')
    print()
    
    print('🏨 ACCOMMODATION:')
    print('-' * 25)
    print('🏨 Name: Budget Inn & Suites Denver')
    print('📍 Location: Near Downtown Denver')
    print('⭐ Rating: 3.2/5.0')
    print('🛏️ Room: Standard Double Room')
    print('💰 Price: $45 per night')
    print('📅 Total (6 nights): $270')
    print('🎯 Amenities: Free WiFi, Continental Breakfast, Shuttle to Airport')
    print()
    
    print('🎿 ACTIVITIES & ATTRACTIONS:')
    print('-' * 35)
    print('Day 1 (Nov 25): Arrival & Denver Exploration')
    print('  • Free Denver Art Museum (2-5 PM)')
    print('  • Walk through downtown (Free)')
    print('  • Cost: $0')
    print()
    print('Day 2 (Nov 26): Rocky Mountain National Park')
    print('  • Park entrance fee: $30 per vehicle')
    print('  • Hiking trails with snow views (Free)')
    print('  • Packed lunch from hotel breakfast')
    print('  • Cost: $30')
    print()
    print('Day 3 (Nov 27): Denver Museums & City')
    print('  • Denver Museum of Nature & Science: $20 per person')
    print('  • 16th Street Mall shopping (Free browsing)')
    print('  • Cost: $40')
    print()
    print('Day 4 (Nov 28): Snow Activities')
    print('  • Day trip to nearby ski area (viewing/free areas)')
    print('  • Local transport: $15 per person')
    print('  • Cost: $30')
    print()
    print('Day 5 (Nov 29): Cultural Denver')
    print('  • Free brewery tours (3 breweries)')
    print('  • Union Station visit (Free)')
    print('  • Cost: $0')
    print()
    print('Day 6 (Nov 30): Final Exploration')
    print('  • Denver Botanic Gardens: $15 per person')
    print('  • Packing and prep for departure')
    print('  • Cost: $30')
    print()
    
    print('🍽️ MEALS:')
    print('-' * 15)
    print('• Breakfast: Included at hotel (Free)')
    print('• Lunch: Budget-friendly ($8-12 per person per day)')
    print('• Dinner: Mix of affordable restaurants ($15-20 per person)')
    print('• Total meal budget: $25 per person per day')
    print('• 6 days × 2 people × $25 = $300')
    print()
    
    print('💰 TOTAL COST BREAKDOWN:')
    print('=' * 35)
    print('✈️ Flights (Business Select): $640')
    print('🏨 Hotels (6 nights): $270') 
    print('🎯 Activities & Entry Fees: $130')
    print('🍽️ Meals (excluding breakfast): $300')
    print('🚗 Local Transport: $50')
    print('📱 Miscellaneous: $50')
    print('-' * 35)
    print('💳 GRAND TOTAL: $1,440')
    print()
    print('⚠️  BUDGET ADJUSTMENT NEEDED:')
    print('Your budget: $1,000')
    print('Projected cost: $1,440') 
    print('Over budget by: $440')
    print()
    print('💡 BUDGET OPTIMIZATION OPTIONS:')
    print('1. 🎫 Switch to Economy flights: Save $300')
    print('2. 🏨 Stay in hostel/shared accommodation: Save $120')  
    print('3. 🍽️ More home-packed meals: Save $150')
    print('4. 🎯 Skip paid attractions, focus on free activities: Save $100')
    print()
    print('✅ OPTIMIZED WITHIN BUDGET:')
    print('✈️ Economy flights: $340')
    print('🏨 Hostel accommodation: $150 (6 nights)')
    print('🎯 Free activities only: $30')
    print('🍽️ Mostly packed meals: $150')
    print('🚗 Public transport: $30')
    print('📱 Miscellaneous: $50')
    print('-' * 35)
    print('💳 OPTIMIZED TOTAL: $750')
    print('💰 Under budget by: $250')
    print()
    print('🎯 FINAL RECOMMENDATION:')
    print('Denver, Colorado offers the perfect snowy destination within budget!')
    print('• ❄️ Guaranteed snow in Rocky Mountains')
    print('• 🎿 Access to winter activities') 
    print('• 🏔️ Beautiful mountain scenery')
    print('• 💰 Budget-friendly with optimization')
    print('• 🎯 Mix of urban and nature experiences')
    print()
    print('🚀 READY TO BOOK:')
    print('Your optimized snowy adventure awaits!')
    print('=' * 70)

if __name__ == "__main__":
    show_budget_friendly_snowy_itinerary()